"use client"

import { useState, useEffect } from "react"
import { useSearchParams, useRouter } from "next/navigation"
import { Snowflakes } from "@/components/snowflakes"
import { Streetlights } from "@/components/streetlights"
import { ChristmasVillage } from "@/components/christmas-village"
import { ChristmasLogin } from "@/components/christmas-login"
import { ChristmasTree } from "@/components/christmas-tree"
import { WellWishesForm } from "@/components/well-wishes-form"
import { CreateTreeModal } from "@/components/create-tree-modal"
import { Button } from "@/components/ui/button"
import { TREE_OWNER_EMAIL } from "@/config/christmas"
import { getTree, signupOrLogin, getUserByTreeId } from "@/app/utils/api"

// Default tree ID fallback (only used if no URL parameter and user hasn't logged in yet)
// This will be replaced by the treeId generated by the backend on user signup
const DEFAULT_TREE_ID = "kiti-tree"

export default function Home() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [userName, setUserName] = useState("")
  const [userEmail, setUserEmail] = useState("")
  const [isInputHovered, setIsInputHovered] = useState(false)
  const [treeId, setTreeId] = useState<string>(() => {
    // Check for treeId in URL first (for sharing)
    if (typeof window !== "undefined") {
      const params = new URLSearchParams(window.location.search)
      return params.get("treeId") || DEFAULT_TREE_ID
    }
    return DEFAULT_TREE_ID
  })
  const [treeName, setTreeName] = useState<string>("Kiti's Christmas Tree")
  const [treeOwnerName, setTreeOwnerName] = useState<string>("")
  const [lastWishMessage, setLastWishMessage] = useState<string>("")
  const [showCreateModal, setShowCreateModal] = useState(false)

  useEffect(() => {
    // Check if user is already logged in from localStorage
    const storedName = localStorage.getItem("christmas_userName")
    const storedEmail = localStorage.getItem("christmas_userEmail")
    const storedTreeId = localStorage.getItem("treeId")
    
    if (storedName && storedEmail && storedTreeId) {
      setUserName(storedName)
      setUserEmail(storedEmail)
      setIsLoggedIn(true)
      // Redirect to tree page
      router.push(`/tree?treeId=${storedTreeId}`)
      return
    }

    // Get treeId from URL parameter if present (for shared trees)
    const urlTreeId = searchParams?.get("treeId")
    if (urlTreeId) {
      setTreeId(urlTreeId)
    }
  }, [searchParams, router])

  useEffect(() => {
    // Load tree info from API
    const loadTreeInfo = async () => {
      try {
        const treeData = await getTree(treeId)
        setTreeName(treeData.treeName || "Kiti's Christmas Tree")
      } catch (error) {
        console.error("Error loading tree info:", error)
        // Fallback to default name if tree not found
        setTreeName("Kiti's Christmas Tree")
      }
    }
    
    // Load tree owner name from API
    const loadTreeOwner = async () => {
      try {
        const userData = await getUserByTreeId(treeId)
        console.log("userDataaa", userData)
        setTreeOwnerName(userData.name || "")
      } catch (error) {
        console.error("Error loading tree owner:", error)
        setTreeOwnerName("")
      }
    }
    
    loadTreeInfo()
    loadTreeOwner()
  }, [])

  const handleLogin = async (name: string, email: string) => {
    try {
      // Call signup API - it will create user if new, or return existing user
      // The backend generates a unique treeId for each user on signup
      const response = await signupOrLogin({
        name: name.trim(),
        email: email.trim().toLowerCase(),
      })
      
      // Store _id as userId and treeId in localStorage
      if (response.user._id) {
        localStorage.setItem("userId", response.user._id)
      }
      localStorage.setItem("treeId", response.user.treeId)
      localStorage.setItem("christmas_userName", response.user.name)
      localStorage.setItem("christmas_userEmail", response.user.email)
      
      // Redirect to /tree?treeId=<treeId>
      router.push(`/tree?treeId=${response.user.treeId}`)
    } catch (error) {
      console.error("Error during login:", error)
      alert(error instanceof Error ? error.message : "Failed to login. Please try again.")
    }
  }

  const handleTreeCreated = async (newTreeId: string) => {
    setTreeId(newTreeId)
    // Load the new tree's name from API
    try {
      const treeData = await getTree(newTreeId)
      setTreeName(treeData.treeName || "Your Christmas Tree")
    } catch (error) {
      console.error("Error loading new tree info:", error)
      setTreeName("Your Christmas Tree")
    }
    setShowCreateModal(false)
  }

  if (!isLoggedIn) {
    return (
      <div className="min-h-screen relative overflow-hidden" style={{ backgroundColor: "#0f4c3a" }}>
        <ChristmasVillage />
        <Snowflakes />
        <Streetlights />
        <div className="relative z-10 flex flex-col items-center justify-center min-h-screen p-4">
          <div className="text-center mb-8 mt-20">
            <h1
              className="text-6xl md:text-7xl lg:text-8xl font-bold mb-4 text-white drop-shadow-2xl"
              style={{ fontFamily: "serif", letterSpacing: "0.05em" }}
            >
              Kiti's Christmas Tree<span style={{ fontSize: "0.6em", marginLeft: "0.1em" }}>❆</span>
            </h1>
            <p className="text-xl md:text-2xl text-white/90 font-light drop-shadow-lg mt-4">
              Decorate the tree and leave your well wishes!
            </p>
          </div>

          {/* Login with lightly blurred houses image behind */}
          <div className="relative z-20 w-full max-w-md mx-auto">
            {/* Background image with increased blur on input hover */}
            <div className={`absolute -inset-6 rounded-[40px] overflow-hidden transition-all duration-300 ${isInputHovered ? 'blur-[8px]' : 'blur-[2px]'}`}>
              <img
                src="/assets/christmas_icons/houses.jpg"
                alt="Cozy Christmas houses"
                className="w-full h-full object-cover"
              />
            </div>

            {/* Login card in front */}
            <div className="relative">
              <ChristmasLogin onLogin={handleLogin} onInputHover={() => setIsInputHovered(true)} onInputBlur={() => setIsInputHovered(false)} />
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen relative overflow-hidden" style={{ backgroundColor: '#0f4c3a' }}>
      <ChristmasVillage />
      <Snowflakes />
      <Streetlights />
      <div className="relative z-10 p-4 py-8">
        {/* Header */}
        <div className="text-center mb-10 mt-6">
          <h1 className="text-4xl md:text-5xl font-bold mb-2 text-white drop-shadow-lg">
             Welcome, {userName}! 🎄
          </h1>
          <p className="text-lg text-white drop-shadow-md">
             leave a secret wish & then scroll down to decorate the tree.
          </p>
        </div>

        {/* Wish section at top */}
        <section className="max-w-4xl mx-auto relative z-20 mb-12">
          <WellWishesForm
            userName={userName}
            userEmail={userEmail}
            treeId={treeId}
            onWishSaved={(wish) => setLastWishMessage(wish)}
          />
        </section>

        {/* Tree section below */}
        <section className="max-w-6xl mx-auto relative z-20 mt-4">
          <div className="text-center mb-4">
            <h2 className="text-3xl md:text-4xl font-semibold text-white drop-shadow-lg">
               Now decorate {treeOwnerName || "the"} 🎄
            </h2>
            <p className="text-white/90 mt-1">
              Choose an ornament and click anywhere on the tree to place it.
            </p>
          </div>
          <ChristmasTree
            userName={userName}
            userEmail={userEmail}
            treeId={treeId}
            lastWishMessage={lastWishMessage}
          />
        </section>

        {/* Create Your Own Tree Button */}
        <section className="max-w-4xl mx-auto relative z-20 mt-16 mb-8">
          <div className="text-center">
            <div className="bg-white/10 backdrop-blur-md rounded-lg p-8 border-2 border-white/20 shadow-xl">
              <h3 className="text-2xl md:text-3xl font-bold text-white mb-4 drop-shadow-md">
                Want Your Own Tree? 🌲
              </h3>
              <p className="text-white/90 mb-6 drop-shadow-sm text-lg">
                Create your own Christmas tree and invite friends to decorate it!
              </p>
              <Button
                onClick={() => setShowCreateModal(true)}
                className="bg-white/20 hover:bg-white/30 text-white border-white/30 backdrop-blur-sm font-bold py-3 px-8 rounded-lg transition-all duration-300 transform hover:scale-105 text-lg shadow-lg"
              >
                🎄 Create Your Own Tree 🎄
              </Button>
            </div>
          </div>
        </section>
      </div>

      {/* Create Tree Modal */}
      {showCreateModal && (
        <CreateTreeModal
          userName={userName}
          userEmail={userEmail}
          onTreeCreated={handleTreeCreated}
          onClose={() => setShowCreateModal(false)}
        />
      )}
    </div>
  )
}
